### ISSUE TITLE
指定端口问题

### ISSUE THREAD

**Issue by Mayter** [zs5460/portscan#1]
不管是-p 1-65535 还是-p 1~65535都不能扫描自定义端口
C:\Users\Administrator\Desktop>portscan.exe -ip 192.168.110.15 -p 0-65535

                      __
    ____  ____  _____/ /_______________ _____
   / __ \/ __ \/ ___/ __/ ___/ ___/ __ \/ __ \
  / /_/ / /_/ / /  / /_(__  ) /__/ /_/ / / / /
 / .___/\____/_/   \__/____/\___/\__,_/_/ /_/
/_/
                                     © zs5460

2020/04/28 22:49:56 Invalid Port

C:\Users\Administrator\Desktop>portscan.exe -ip 192.168.110.15 -p 0~65535

                      __
    ____  ____  _____/ /_______________ _____
   / __ \/ __ \/ ___/ __/ ___/ ___/ __ \/ __ \
  / /_/ / /_/ / /  / /_(__  ) /__/ /_/ / / / /
 / .___/\____/_/   \__/____/\___/\__,_/_/ /_/
/_/
                                     © zs5460

2020/04/28 22:50:01 Invalid Port

C:\Users\Administrator\Desktop>portscan.exe -ip 192.168.110.15 -p 80

**Comment by zs5460** [comment]
因为已经有全扫描和常用端口扫描了，所以自定义端口扫描只支持单个端口
